/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as ProductsRepackagedImport } from './routes/products/repackaged'
import { Route as ProductsPodImport } from './routes/products/pod'
import { Route as ProductsOriginalImport } from './routes/products/original'
import { Route as ProductsNightmareImport } from './routes/products/nightmare'
import { Route as ProductsProductCodeImport } from './routes/products/$product-code'
import { Route as CardsCardSlugImport } from './routes/cards/$card-slug'
import { Route as CardsSearchIndexImport } from './routes/cards/search/index'
import { Route as CardsSearchAdvancedImport } from './routes/cards/search/advanced'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsRepackagedRoute = ProductsRepackagedImport.update({
  id: '/products/repackaged',
  path: '/products/repackaged',
  getParentRoute: () => rootRoute,
} as any)

const ProductsPodRoute = ProductsPodImport.update({
  id: '/products/pod',
  path: '/products/pod',
  getParentRoute: () => rootRoute,
} as any)

const ProductsOriginalRoute = ProductsOriginalImport.update({
  id: '/products/original',
  path: '/products/original',
  getParentRoute: () => rootRoute,
} as any)

const ProductsNightmareRoute = ProductsNightmareImport.update({
  id: '/products/nightmare',
  path: '/products/nightmare',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductCodeRoute = ProductsProductCodeImport.update({
  id: '/products/$product-code',
  path: '/products/$product-code',
  getParentRoute: () => rootRoute,
} as any)

const CardsCardSlugRoute = CardsCardSlugImport.update({
  id: '/cards/$card-slug',
  path: '/cards/$card-slug',
  getParentRoute: () => rootRoute,
} as any)

const CardsSearchIndexRoute = CardsSearchIndexImport.update({
  id: '/cards/search/',
  path: '/cards/search/',
  getParentRoute: () => rootRoute,
} as any)

const CardsSearchAdvancedRoute = CardsSearchAdvancedImport.update({
  id: '/cards/search/advanced',
  path: '/cards/search/advanced',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cards/$card-slug': {
      id: '/cards/$card-slug'
      path: '/cards/$card-slug'
      fullPath: '/cards/$card-slug'
      preLoaderRoute: typeof CardsCardSlugImport
      parentRoute: typeof rootRoute
    }
    '/products/$product-code': {
      id: '/products/$product-code'
      path: '/products/$product-code'
      fullPath: '/products/$product-code'
      preLoaderRoute: typeof ProductsProductCodeImport
      parentRoute: typeof rootRoute
    }
    '/products/nightmare': {
      id: '/products/nightmare'
      path: '/products/nightmare'
      fullPath: '/products/nightmare'
      preLoaderRoute: typeof ProductsNightmareImport
      parentRoute: typeof rootRoute
    }
    '/products/original': {
      id: '/products/original'
      path: '/products/original'
      fullPath: '/products/original'
      preLoaderRoute: typeof ProductsOriginalImport
      parentRoute: typeof rootRoute
    }
    '/products/pod': {
      id: '/products/pod'
      path: '/products/pod'
      fullPath: '/products/pod'
      preLoaderRoute: typeof ProductsPodImport
      parentRoute: typeof rootRoute
    }
    '/products/repackaged': {
      id: '/products/repackaged'
      path: '/products/repackaged'
      fullPath: '/products/repackaged'
      preLoaderRoute: typeof ProductsRepackagedImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/cards/search/advanced': {
      id: '/cards/search/advanced'
      path: '/cards/search/advanced'
      fullPath: '/cards/search/advanced'
      preLoaderRoute: typeof CardsSearchAdvancedImport
      parentRoute: typeof rootRoute
    }
    '/cards/search/': {
      id: '/cards/search/'
      path: '/cards/search'
      fullPath: '/cards/search'
      preLoaderRoute: typeof CardsSearchIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards/$card-slug': typeof CardsCardSlugRoute
  '/products/$product-code': typeof ProductsProductCodeRoute
  '/products/nightmare': typeof ProductsNightmareRoute
  '/products/original': typeof ProductsOriginalRoute
  '/products/pod': typeof ProductsPodRoute
  '/products/repackaged': typeof ProductsRepackagedRoute
  '/products': typeof ProductsIndexRoute
  '/cards/search/advanced': typeof CardsSearchAdvancedRoute
  '/cards/search': typeof CardsSearchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards/$card-slug': typeof CardsCardSlugRoute
  '/products/$product-code': typeof ProductsProductCodeRoute
  '/products/nightmare': typeof ProductsNightmareRoute
  '/products/original': typeof ProductsOriginalRoute
  '/products/pod': typeof ProductsPodRoute
  '/products/repackaged': typeof ProductsRepackagedRoute
  '/products': typeof ProductsIndexRoute
  '/cards/search/advanced': typeof CardsSearchAdvancedRoute
  '/cards/search': typeof CardsSearchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cards/$card-slug': typeof CardsCardSlugRoute
  '/products/$product-code': typeof ProductsProductCodeRoute
  '/products/nightmare': typeof ProductsNightmareRoute
  '/products/original': typeof ProductsOriginalRoute
  '/products/pod': typeof ProductsPodRoute
  '/products/repackaged': typeof ProductsRepackagedRoute
  '/products/': typeof ProductsIndexRoute
  '/cards/search/advanced': typeof CardsSearchAdvancedRoute
  '/cards/search/': typeof CardsSearchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards/$card-slug'
    | '/products/$product-code'
    | '/products/nightmare'
    | '/products/original'
    | '/products/pod'
    | '/products/repackaged'
    | '/products'
    | '/cards/search/advanced'
    | '/cards/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards/$card-slug'
    | '/products/$product-code'
    | '/products/nightmare'
    | '/products/original'
    | '/products/pod'
    | '/products/repackaged'
    | '/products'
    | '/cards/search/advanced'
    | '/cards/search'
  id:
    | '__root__'
    | '/'
    | '/cards/$card-slug'
    | '/products/$product-code'
    | '/products/nightmare'
    | '/products/original'
    | '/products/pod'
    | '/products/repackaged'
    | '/products/'
    | '/cards/search/advanced'
    | '/cards/search/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsCardSlugRoute: typeof CardsCardSlugRoute
  ProductsProductCodeRoute: typeof ProductsProductCodeRoute
  ProductsNightmareRoute: typeof ProductsNightmareRoute
  ProductsOriginalRoute: typeof ProductsOriginalRoute
  ProductsPodRoute: typeof ProductsPodRoute
  ProductsRepackagedRoute: typeof ProductsRepackagedRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  CardsSearchAdvancedRoute: typeof CardsSearchAdvancedRoute
  CardsSearchIndexRoute: typeof CardsSearchIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsCardSlugRoute: CardsCardSlugRoute,
  ProductsProductCodeRoute: ProductsProductCodeRoute,
  ProductsNightmareRoute: ProductsNightmareRoute,
  ProductsOriginalRoute: ProductsOriginalRoute,
  ProductsPodRoute: ProductsPodRoute,
  ProductsRepackagedRoute: ProductsRepackagedRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  CardsSearchAdvancedRoute: CardsSearchAdvancedRoute,
  CardsSearchIndexRoute: CardsSearchIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cards/$card-slug",
        "/products/$product-code",
        "/products/nightmare",
        "/products/original",
        "/products/pod",
        "/products/repackaged",
        "/products/",
        "/cards/search/advanced",
        "/cards/search/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cards/$card-slug": {
      "filePath": "cards/$card-slug.tsx"
    },
    "/products/$product-code": {
      "filePath": "products/$product-code.tsx"
    },
    "/products/nightmare": {
      "filePath": "products/nightmare.tsx"
    },
    "/products/original": {
      "filePath": "products/original.tsx"
    },
    "/products/pod": {
      "filePath": "products/pod.tsx"
    },
    "/products/repackaged": {
      "filePath": "products/repackaged.tsx"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    },
    "/cards/search/advanced": {
      "filePath": "cards/search/advanced.tsx"
    },
    "/cards/search/": {
      "filePath": "cards/search/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
